
# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
# license that can be found in the LICENSE file.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: installerj
  labels: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: installer
  template:
    metadata:
      labels:
        app: installer
    spec:
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsUser: 1001
      containers:
      - name: installer
        image: nandajavarma/installer:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: installer
  annotations:
    k8s-tunnel-controller/tunnel: installer-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: installer
    protocol: TCP
    targetPort: 8080
  selector:
    app: installer
