apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: crossplane-provider-gcp
  namespace: crossplane-system
spec:
  projectID: sh-automated-tests
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-account-creds
      key: credentials
